### ISSUE TITLE
Write project proposal / Update README.md

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/CPD#12]
The  project proposal stands to be updated based on tiff's feedback about using a linear regression model to see if there is a correlation between salary and complaint rate (and including other explanatory/demographic variables).

@micahkwok, let me know if you need help here as I am happy to make this change.

**Comment by elabandari** [comment]
I updated the project proposal to reflect tiff's suggestions. Please keep me updated on your thoughts about the updated version.

**Comment by micahkwok** [comment]
Thanks for changing it Ela! Just some thoughts for us to remember is before we 'submit' we should double-check again that these contents match up with our eda & other files
