### ISSUE TITLE
Scope all tasks related to milestone 2

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/CPD#19]
Hi @micahkwok and @ebs33,

Do you think it would be helpful to have a scoping meeting on Monday (maybe at 12:30-1:00 PM) to review the requirements for Milestone 2 and roughly assign tasks?

Alternatively, we can do this during class time on Tuesday.

**Comment by micahkwok** [comment]
I'd prefer to do this Tuesday in the time Tiffany allocates for us because she might give further insight into Milestone 2 during the first half of class.

**Comment by eboylestanley** [comment]
I am okay with waiting until Tuesday.  Can we commit that we will read the milestone 2 requirements in advance?  This way we can use the Tuesday lecture as a working session?

**Comment by micahkwok** [comment]
Sounds good to me

**Comment by elabandari** [comment]
Great suggestion, chat in class tomorrow!
