### ISSUE TITLE
Script 3 : exploratory data visualization and table

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/CPD#23]

**Comment by eboylestanley** [comment]
EDA Plots:
- Complaints per year
- CPD Staff per year
- Number of Complaints per officer
- Number of Complaints per officer facet by year
- Number of Complaints by rank
- Salary distribution by rank (isolate by Police Officer Rank)
- Age distribution - pick 2015 as example.  Check 2015 is representative of other years.  (isolate by Police Officer Rank)
- Years of service - pick 2015 as example.  Check 2015 is representative of other years.  (isolate by Police Officer Rank)
- Gender bar chart  (isolate by Police Officer Rank)
- Race bar chart  (isolate by Police Officer Rank)
- Complaint rate correlation to salary, age, gender, race, years of service  (isolate by Police Officer Rank)

**Comment by micahkwok** [comment]
Self-Checklist (Plots created in notebook)

- [x] Complaints per year
- [x] CPD Staff per year
- [x] Number of Complaints per officer
- [x] Number of Complaints per officer facet by year
- [x] Number of Complaints by rank
- [x] Salary distribution by rank (isolate by Police Officer Rank)
- [x] Age distribution - pick 2015 as example. Check 2015 is representative of other years. (isolate by Police Officer Rank)
- [x] Years of service - pick 2015 as example. Check 2015 is representative of other years. (isolate by Police Officer Rank)
- [x] Gender bar chart (isolate by Police Officer Rank)
- [x] Race bar chart (isolate by Police Officer Rank)
- [x] Complaint rate correlation to salary, age, years of service (isolate by Police Officer Rank)

**Comment by micahkwok** [comment]
```Rscript generate_EDA_figures.r --all_data=../data/complaints_all_staff.csv --police_data=../data/complaints_police.csv --out_dir=../eda/images```

**Comment by elabandari** [comment]
Hi @micahkwok,

Great work on the most recent PR. The plots all look great.

One minor heads-up, your corr_matrix doesn't render in the EDA.ipynb file but it looks great as a .png in your images.

**Comment by micahkwok** [comment]
Oh, sorry, I think it was cause I was testing that cell because I had to use a different method in the script in order to save the image, so the output of that cell probably became a saved image instead. I can change that later for the next pull request. If its urgent, I think if you remove everything that isn't part of the assignment <- part of the code, it'll be able to produce the object. Otherwise it may keep generating a test image everytime we run the EDA.ipynb file. 

Good catch!

**Comment by elabandari** [comment]
Yea, no worries. Feel free to batch it with the next PR.
