### ISSUE TITLE
What is `cv` field related to?

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/CPD#26]

**Comment by eboylestanley** [comment]
I can't find any information on this field in the 
chicago-police-data github repo documentation.  At this point, I don't believe it is relevant to our project and think we should pass on further investigation.

**Comment by elabandari** [comment]
Hi  @ebs33,

From the [data dictionary,](https://github.com/invinst/chicago-police-data/blob/master/data/unified_data/data-dictionary/data-dictionary.yaml) we see that cv = version of complaints where row originated (1 = 1967-1999, 2 = 2000-2016, 3 = 2000 - 2018). 

So we only want to look at cv2 and 3 based on our scope which is what you have already done in the cleaning step last week :-)

**Comment by eboylestanley** [comment]
Thanks @elabandari! I will adjust the data cleaning process accordingly, I actually filtered out cv 2 & 3 for the duplicate records.
