### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/CPD#27]
I enjoyed reading this proposal. It was very clear and you made a good story. I understand you said that your knowledge of linear regression/ML would evolve, but it would be good to state other models you might use especially since this could be a multivariable problem.

**Comment by elabandari** [comment]
Hi Arjun, 

Thank you for the feedback. We have decided on to test a couple of linear regression models including a multivariable model with demographics variables. We will be sure to update our project report to include these.
