### ISSUE TITLE
Separating raw and processed data

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/CPD#37]
Hi @ebs33 and @micahkwok, 

I have separated the data directory into raw and processed data. I have also updated the usage section of the README.md to reflect this change. There is a PR up with these changes. 

I have double checked that this should not affect our scripts since our scripts take flexible input file paths but let me know if that is the case.

**Comment by micahkwok** [comment]
Yep thanks! I think our scripts are flexible too, I left a comment on the PR

**Comment by elabandari** [comment]
Thanks for the speedy review @micahkwok. Updated PR should be up shortly.
