### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/CPD#39]
Hi @ebs33 and @micahkwok, 

Do modules such as OS that are included as part of Python’s standard utility module need to be included in our dependencies?

**Comment by micahkwok** [comment]
I don't think so, Tiffany's example only has the following dependencies on her Readme as below. 

![Screen Shot 2020-11-27 at 4 13 28 PM](https://user-images.githubusercontent.com/70661726/100489804-7d15b100-30cb-11eb-8dd8-251b9f7a8c4c.png)

**Comment by elabandari** [comment]
Alright, gzip also falls under a similar category since it comes installed with your OS.

**Comment by elabandari** [comment]
So, I think we can remove OS and gzip from our dependencies list in the README.md.

**Comment by eboylestanley** [comment]
Whoops agreed!  I quickly scanned our scripts and just pulled out all the packages I saw at first glance.
