### ISSUE TITLE
Double checking licensing for CPD datasets 

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/CPD#4]
Just wanted a second pair of eyes to confirm that this data is alright to use for our project. 

The README.md indicates "We have collected these datasets in this repository so that everyone can analyze and investigate police accountability in Chicago using a common body of evidence." 

https://github.com/invinst/chicago-police-data

**Comment by micahkwok** [comment]
I have the same conclusion that the data is okay to use for our project.
