### ISSUE TITLE
Peer review feedback for CPD team

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/CPD#60]
Hello CPD team,

Great work! I really enjoyed reading your report and exploring your project. You chose an interesting question. I only have few comments/ suggestions for your report and readme files.

### Documentation

Yes. It is great. All scripts have been sufficiently documented.

### Reprocibility
Yes. It is great. I have cloned the repository and ran it on my computer. It ran smoothly on my laptop.

### Readme:
- You can elaborate more on your question in the Readme. It was not not clear to me before reading your report.
- There is a small typo in the usage section of the Readme file. 
"command lin"
- You can also update the usage section to use a Makefile for reproducing your results.

### Report:

- It would be a good idea to push the markdown of your report as well in your repository.
- Graet work on providing very detailed EDA in your report. However, you can also remove some of the EDA figures from your report and just include the ones that is important for your analysis. 
- You can make a more descriptive title for your report.
- missing date last edited.
- The resolution of plots is low, and it is hard to see some of the labels, especially in Figures 1, 2, 5 and 7.
- It would be a good idea to make a section at the end of your report to summarize and discuss your results. 

Great work!

**Comment by elabandari** [comment]
Hi @Kamal12073 

Thank you for taking the time to give us feedback. Below is our response to your feedback.

It would be a good idea to push the markdown of your report as well in your repository.
- We were concerned about having too many documents in our docs directory. We think the .Rmd and should be sufficient.

Great work on providing very detailed EDA in your report. However, you can also remove some of the EDA figures from your report and just include the ones that is important for your analysis.
- Thank you this has been done~ 

You can make a more descriptive title for your report.
- Completed

missing date last edited.
- Completed

The resolution of plots is low, and it is hard to see some of the labels, especially in Figures 1, 2, 5 and 7.
- Completed

It would be a good idea to make a section at the end of your report to summarize and discuss your results.
- We are have made the discussion more through by expanding on our analyses and adding a limitations section.
